#%RAML 0.8
title: 课程管理API
baseUri: http://zizibujuan.com
version: v0.1
/courses:
  displayName: Courses
  post:
    description: 登录用户添加课程
    body:
      application/x-www-form-urlencoded:
        formParameters:
          name:
            description: 课程名称
            type: string
            required: true
            maxLength: 64
          description:
            description: 课程描述
            type: string
            required: false
    responses:
      201:
        description: 登录用户添加课程成功
        body:
          application/json:
            schema: |
              {
                "id": 1              
              }
      412:
        description: 登录用户已使用课程名称
        body:
          application/json:
            schema: |
              {
                "type": "field",
                "errors": [
                  {
                    "field": "name", 
                    "message": "课程名已被使用 | 课程名不能为空 | 课程名称最多32个字"
                  }
                ]
              }
  /check-name:
    post:
      queryParameters:
        owner:
          type: string
          description: 用户标识
      body:
        application/x-www-form-urlencoded:
          formParameters:
            value:
              description: 课程名
              type: string
      responses:
        200:
          description: 登录用户没有使用指定的课程名称
          body:
            application/json:
              schema: |
                {
                  "name": "course1"
                }
        403:
          description: 登录用户已经使用了课程名称
          body:
            application/json:
              schema: |
                {
                  "message": "课程名已被使用"
                }              