#%RAML 0.8
title: 课程表管理API
baseUri: http://zizibujuan.com
version: v0.1
/curricula:
  description: 维护课程表，可使用日历控件维护。
  displayName: Curriculum Schedule
  post:
    description: 登录用户在课程表中新增课程
    body:
      application/x-www-form-urlencoded:
        formParameters:
          startTime:
            description: 开始时间，日期+时间
            type: date
            example: "2014-01-01 9:00"
          endTime:
            description: 结束时间，日期+时间
            type: date
            example: "2014-01-01 10:00"
          classId:
            description: 班级标识
            type: integer
          courseId:
            description: 课程标识
            type: integer
          lessonId:
            description: 课时标识
            type: integer
    responses:
      201:
        description: 登录用户安排课时成功
        body:
          application/json:
            schema: |
              {
                "id": ""
              }
  /{curriculumId}/events:
    description: 获取登录用户即将开始的课程，默认为提前15分钟通知
    get:
      queryParameters:
        type:
          type: string
          required: true
          default: "incoming"
          example: "incoming"
      responses:
        200:
          description: |
            如果type为"incoming",则获取即将开始的课程，如果没有则返回空数组
          body:
            application/json:
              schema: |
                [{
                  "lessonId": 1,
                  "courseName": "course1",
                  "lessonName": "lesson1"
                }]